- pipeline:
    name: check
    post-review: true
    manager: independent
    trigger:
      github_conn:
        event:
          - pull_request
        action:
          - opened
          - changed
          - comment
        comment:
          - '^recheck.*$'
    success:
      github_conn:
        comment: true
        status: success
    failure:
      github_conn:
        comment: true
        status: failure
    merge-failure:
      github_conn:
        comment: true
        status: failure
    start:
      github_conn:
        comment: true
        status: pending
    disabled:
      github_conn:
        comment: true


- project:
    name: jluk-codi-org/zuul-test
    check:
      jobs:
        - noop

- job:
    name: base
    parent: null
    pre-run: base-playbook.yaml
